gutenberg/acquire/text.py
tests/data/sample-metadata/23962
tests/test_acquire.py

The current version uses ISO-8859-1 as the encoding to download Gutenberg ebooks. However this restricts the languages that this library can download ([see here](http://en.wikipedia.org/wiki/ISO/IEC_8859-1#Languages_with_complete_coverage)).
For example, the current version cannot download Chinese texts. The changes I have made fixes that by changing the `requests.get` encoding to `utf-8`. Below is a script that downloads [Journey to the West](http://www.gutenberg.org/ebooks/23962), a Chinese ebook, and saves it using the appropriate encoding.
```
from gutenberg.acquire import load_etext
from gutenberg.cleanup import strip_headers
OUTFILE = "<insert outfile destination here>"
text = strip_headers(load_etext(23962)).strip()
with open(OUTFILE, 'w') as f:
f.write(text)
```

Added support for downloading texts from more languages

---

README.rst

I know someone who was a bit surprised there was only title and author metadata available after leaving it to run overnight building the database.
So perhaps it should be made a bit clearer that there's only title and author available. Perhaps something like this?

Make it explicit what metadata is available

---

gutenberg/query/extractors.py
tests/_sample_metadata.py
tests/data/sample-metadata/30929
tests/test_query.py

I need to be able to return all available URIs for an ebook, specified by the hasFormat predicate in the RDF graph. This does that.
~~~
vagrant@ol-dev:/openlibrary/Gutenberg$ python -c "from gutenberg.query import get_metadata; print(get_metadata('formaturi', 2701))"
INFO:rdflib:RDFLib Version: 4.2.1
frozenset([u'http://www.gutenberg.org/files/2701/2701.txt',
u'http://www.gutenberg.org/files/2701/2701.zip',
u'http://www.gutenberg.org/ebooks/2701.rdf',
u'http://www.gutenberg.org/ebooks/2701.kindle.images',
u'http://www.gutenberg.org/ebooks/2701.epub.images', 
u'http://www.gutenberg.org/ebooks/2701.epub.noimages', 
u'http://www.gutenberg.org/files/2701/2701-h/2701-h.htm', 
u'http://www.gutenberg.org/ebooks/2701.kindle.noimages', 
u'http://www.gutenberg.org/files/2701/2701-h.zip', …

Add an extractor to return a list of eBook URIs

---

.travis.yml
requirements.pip

html5lib requires setuptools version 18.5 or above; please upgrade before installing (you have 12.0.5)
This does leave Python 3.2 still broken, but that's for a completely different reason.

fix broken dependency for SQLAlchemy on travis

---

gutenberg/_domain_model/vocabulary.py
gutenberg/query/api.py
gutenberg/query/extractors.py
tests/_sample_metadata.py
tests/test_query.py

I've added extractors for more metadata information. As an example, here's the results for Moby Dick:
````
get_metadata('title', 2701) : frozenset({'Moby Dick; Or, The Whale'})
get_metadata('author', 2701) : frozenset({'Melville, Hermann'})
get_metadata('rights', 2701) : frozenset({'Public domain in the USA.'})
get_metadata('subject', 2701) : frozenset({'Adventure stories', 'Sea stories', 'Whales -- Fiction', 'Psychological fiction', 'Whaling ships -- Fiction', 'Ahab, Captain (Fictitious character) -- Fiction', 'Whaling -- Fiction', 'Mentally ill -- Fiction', 'Ship captains -- Fiction', 'PS'})
get_metadata('language', 2701) : frozenset({rdflib.term.Literal('en', datatype=rdflib.term.URIRef('http://purl.org/dc/terms/RFC4646'))})
````

Additional RDF metadata extractors for language, subject(s), and copyright

---

.coveragerc
.gitignore
.travis.yml

This uses the Coverage.py tool to measure the coverage of the unit tests.
Coverage is currently an impressive 94%!
https://coveralls.io/builds/8570591
It gives a report of the coverage on the CI with `coverage report`:
https://travis-ci.org/hugovk/Gutenberg/jobs/171618837#L211
And also sends the data to Coveralls, which is handy to track progress and show coverage of individual files:
https://coveralls.io/github/hugovk/Gutenberg
Please could an admin also enable Coveralls at https://coveralls.io/repos/new? It's free for open source :)
If you're developing locally, you can use `coverage html` to generate similar reports in htmlcov/index.html

Run tests with coverage

---

gutenberg/acquire/text.py
tests/test_acquire.py

Fix encoding issue reported in #62

---

gutenberg/acquire/text.py

Precondition, no cached etext no. 1: 
```bash
rm ~/gutenberg_data/text/1.txt.gz
```
With this code:
```python
from gutenberg.acquire import load_etext
text = load_etext(1)
print(text)[:200]
```
Results in:
```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /etext90/when11.txt was not found on this server.</p>
```
With this PR, results in:
```txt
===========================================================
NOTE:  This file combines the first two Project Gutenberg
files, both of which were given the filenumber #1. There are
```
A similar thing happens for etexts 1-9.
Previously the URI for etexts 1-9 were special cases like:
http://www.gutenberg.lib.md.us/etext90/when11.txt
But now they're …

Fix load_etext for etexts 1-9

---

gutenberg/_domain_model/types.py
gutenberg/query/api.py
gutenberg/query/extractors.py
tests/_sample_metadata.py
tests/data/sample-metadata/14287
tests/data/sample-metadata/23962
tests/data/sample-metadata/30929

- Add more data for metadata querying tests
- Fix test setup
This PR resolves #70.

Fix metadata extractors

---

gutenberg/query/api.py
gutenberg/query/extractors.py
tests/_sample_metadata.py
tests/data/sample-metadata/0
tests/test_query.py

This is a partial fix for the [issue](https://github.com/c-w/Gutenberg/issues/57#issuecomment-262246622) reported by @ikarth on #57.

Prevent phantom metadata from crashing queries

---

.gitignore
gutenberg/_util/decorators.py
gutenberg/acquire/text.py
tests/test_acquire.py

Closes #81
General usage for allowing the end user to specify a mirror to use:
```
$ python3 -m gutenberg.acquire.text 2701 moby-raw.txt
INFO:rdflib:RDFLib Version: 4.2.2
http://aleph.gutenberg.org/2/7/0/2701/2701.txt
$ python3 -m gutenberg.acquire.text --mirror http://mirrors.xmission.com/gutenberg/ 2701 moby-raw.txt
INFO:rdflib:RDFLib Version: 4.2.2
http://mirrors.xmission.com/gutenberg/2/7/0/2701/2701.txt
$ GUTENBERG_MIRROR=http://mirrors.xmission.com/gutenberg/ python3 -m gutenberg.acquire.text 2701 moby-raw.txt
INFO:rdflib:RDFLib Version: 4.2.2
http://mirrors.xmission.com/gutenberg/2/7/0/2701/2701.txt
$ GUTENBERG_MIRROR=http://mirrors.xmission.com/gutenberg/ python3 -m gutenberg.acquire.text --mirror http://eremita.di.uminho.pt/gutenberg/ 2701 moby-raw.txt
INFO:rdflib:RDFLib Version: …
```

Change mirrors and make it easier for end users to switch

---

tests/_sample_metadata.py
tests/_util.py
tests/test_acquire.py

We can run this test every day via the [Travis cron feature](https://docs.travis-ci.com/user/cron-jobs/) to alert us to changes in the environment that may change the mirror we're using for the texts and prevent issues like #81 affecting our users in the future.
Also: some minor test cleanups.

Add integration test for load_etext

---

README.rst

This package isn't the easiest to set up: getting BSD-DB installed is finicky, building the metadata store takes a long time and takes up a lot of disk space, etc.
To remedy this, I set up a hosted version of the library: [gutenberg-http](https://github.com/c-w/gutenberg-http) ([demo page](https://c-w.github.io/gutenberg-http/)).
Mentioning all the core-contributors @hugovk @MasterOdin @sethwoodworth in case you'd like to take a look and maybe help out :)

Add link to http API

---

.travis.yml
README.rst
tests/_sample_metadata.py
tests/_util.py
tests/test_acquire.py
tests/test_domain_model.py
tests/test_metadata_cache.py
tests/test_query.py
tests/test_strip_headers.py
tests/test_util.py

* https://en.wikipedia.org/wiki/CPython#Version_history
* https://snarky.ca/stop-using-python-2-6/
* http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html
* Current pip 9 deprecates Python 2.6 support, pip 10 won't support it (https://github.com/pypa/pip/issues/3955)
* Not much PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796
* pip 10 will deprecate Python 3.3 support, pip 11 won't support it (https://github.com/pypa/pip/issues/3796)
* Very little PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796

Remove unsupported Python 2.6 and 3.3

---

.gitignore
setup.py

setuptools 38.0 made it so that install_requires must be an ordered sequence (so that they can do deterministic builds): https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v3800. We are currently declaring them as sets so therefore the package will break on PyPI for anyone using the newest versions of setuptools.
After this is merged, we should also then bump up the version (to 0.5.1?) so that we get a fix on PyPI for people and which would then also incidently fix python 3.6 testing for c-w/gutenberg-http#3 to be merged. The only real change that's occurred since last release was removing support for Python 2.6 and 3.3.

setuptools >38 needs install_requires to be a list

---

setup.py

as 0.6.0 was ruined with a bad requires_python

Bump setup.py to 0.6.1

---

.travis.yml
README.rst

The Travis logs show that the coveralls repo seems to have disappeared (error: "Couldn't find a repository matching this job.") so this change is moving the project from coveralls to codecov.

Move from coveralls to codecov

---

.travis.yml

I noticed that yesterday that Travis failed unusually only Python 3.4 and then 2.7 in a subsequent build in their build environment. However, we don't really need the Python version itself as everything is done within containers.
This also better handles the future where it's unlikely that Python 3.7 will be supported on Travis for Trusty and Python 3.4 won't be supported on Xenial/Bionic, both of which we want to support in gutenberg for the time being.

Switch to using build matrix for python versions

---

README.rst

Libdb5.1-dev is not available for Ubuntu 16.04. libdb++-dev works in its place for this project.

Changed linux install from libdb5.1-dev to libdb++-dev

---

setup.py

If the file encoding on your system (Linux, Windows, etc) is not set to utf-8, this line could cause problems when reading non-ascii characters from the Readme. This simplifies the `open()` statement so that the pip installation is less dependent on system variables.

Updating encoding for file open

---

.travis.yml

When releasing a new version, the current Travis configuration attempts to deploy the code to PyPI for every Python version. PyPI releases are now immutable so the build's behavior causes errors (see [sample build](https://travis-ci.org/c-w/gutenberg/builds/576317320). Gating the PyPI upload to a single Python version fixes this behavior.

Fix multiple deploys to PyPI

---

azure-pipelines.yml
setup.py

rdflib 5.0.0 reworked some amount of their interface, which breaks things here. Minimally, SPARQLWrapper is no longer used, and a requests based wrapper internal to rdflib is now used, which breaks compatibility with older RDF stores that do not follow the SPARQL Protocol 1.1 spec. Setting this to minimize the break here, with a look to move to rdflib 5 in the next major version bump of gutenberg itself.

Add upper version limit for rdflib

---

setup.py

Once merged, I can make a new release with the following description:
* 20043534ebec8a4ef4f7409f006d5ce4e0a3ef53 - Specify upper-bound on version of rdflib dependecy
* 42d95f05b25ac52a6c4896bf44030018d1afc627 - Add support for Python 3.8

Update version to 0.8.1

---

.coveragerc
setup.py

The CI on MacOS and Python 2.7 started failing when bsddb 6.2.8 was released (see [failed build log](https://clewolff.visualstudio.com/gutenberg/_build/results?buildId=1410&view=logs&j=5f8b5a4a-0b9d-5350-fd1f-b70854064a4e&t=e1dbd89e-54a5-5e77-0e95-3a01560a81d2) and [failed build screenshot](https://user-images.githubusercontent.com/1086421/99916244-f92c8500-2cd6-11eb-9496-c03eaa55eb76.png)).
Given that Python 2.7 is deprecated, this pull request works around the issue by pinning bsddb to 6.2.7 or earlier for the affected combination of OS and Python version (see [successful build log](https://clewolff.visualstudio.com/gutenberg/_build/results?buildId=1411&view=logs&j=5f8b5a4a-0b9d-5350-fd1f-b70854064a4e&t=e1dbd89e-54a5-5e77-0e95-3a01560a81d2)).

Fix install on MacOS with Python 2.7

---

gutenberg/acquire/text.py

`aleph.gutenberg.org` seems down:

Update text download mirror
